<template>
  <main class="page"><header><h1>Scheduled jobs</h1></header>
    <p v-if="error" class="error" role="alert">{{ error }}</p><div v-if="loading" class="empty">Loading schedules…</div>
    <section v-else class="grid"><article v-for="schedule in schedules" :key="schedule.name" class="card"><div class="heading"><div><h2>{{ schedule.displayName }}</h2><code>{{ schedule.cronExpression }}</code></div><span class="tag" :class="{disabled:!schedule.enabled}">{{ schedule.enabled?'Enabled':'Disabled' }}</span></div><dl><div><dt>Time zone</dt><dd>{{ schedule.timeZoneId }}</dd></div><div><dt>Last evaluated</dt><dd>{{ formatOptional(schedule.lastEvaluatedAt) }}</dd></div><div><dt>Next run</dt><dd>{{ formatOptional(schedule.nextOccurrenceAt) }}</dd></div><div><dt>Current job</dt><dd><RouterLink v-if="schedule.currentJob" :to="{name:'jobs-detail',params:{id:schedule.currentJob.id}}">#{{ schedule.currentJob.id }} · {{ schedule.currentJob.status }}</RouterLink><span v-else>—</span></dd></div><div><dt>Last started</dt><dd><RouterLink v-if="schedule.lastStartedJob" :to="{name:'jobs-detail',params:{id:schedule.lastStartedJob.id}}">#{{ schedule.lastStartedJob.id }} · {{ schedule.lastStartedJob.status }}</RouterLink><span v-else>—</span></dd></div></dl><button type="button" :disabled="running===schedule.name" @click="run(schedule.name)">{{ running===schedule.name?'Queuing…':'Run now' }}</button></article></section>
  </main>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { RouterLink } from 'vue-router'; import { listSchedules, runSchedule, type ScheduledJob } from './operationalHistoryApi';
const schedules=ref<ScheduledJob[]>([]);const loading=ref(false);const running=ref<string|null>(null);const error=ref<string|null>(null);onMounted(load);
async function load(){loading.value=true;error.value=null;try{schedules.value=await listSchedules();}catch(reason){error.value=reason instanceof Error?reason.message:'Schedules could not be loaded.';}finally{loading.value=false;}}
async function run(name:string){running.value=name;error.value=null;try{await runSchedule(name);await load();}catch(reason){error.value=reason instanceof Error?reason.message:'The job could not be queued.';}finally{running.value=null;}}
function formatOptional(value:string|null){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';}
</script>
<style scoped>
.page{width:min(1180px,calc(100% - 40px));margin:0 auto;padding:48px 0 64px}h1{margin:0;font:620 clamp(2.2rem,5vw,4rem)/1 var(--font-display)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:26px}.card{padding:20px;border:1px solid var(--border);border-radius:16px;background:var(--surface)}.heading{display:flex;justify-content:space-between;gap:14px}h2{margin:0 0 8px;font-size:1.1rem}code{color:var(--accent-soft)}.tag{height:max-content;padding:5px 8px;border-radius:999px;color:var(--success);background:rgba(95,211,151,.08);font-size:.72rem}.tag.disabled{color:var(--text-muted);background:rgba(255,255,255,.05)}dl{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}dt{color:var(--text-dim);font-size:.72rem}dd{margin:5px 0 0;font-size:.84rem}a{color:var(--accent)}button{padding:10px 13px;border:1px solid var(--accent);border-radius:9px;color:#21170a;background:var(--accent);font:inherit;font-weight:700;cursor:pointer}.error{color:var(--danger-text)}.empty{color:var(--text-muted)}@media(max-width:760px){.grid{grid-template-columns:1fr}}
</style>
