// <auto-generated />
using System;
using LyrionVoiceMcp.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LyrionVoiceMcp.Ef.Migrations
{
    [DbContext(typeof(LyrionVoiceMcpDbContext))]
    [Migration("20260822104213_MakeRatingsSearchable")]
    partial class MakeRatingsSearchable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumArtistSourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtworkTrackSourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCompilation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumArtistSourceId");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CatalogueAlbums", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CatalogueArtists", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueArtistLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CatalogueArtistLookups", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CatalogueGenres", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtistCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenreCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshId")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceLastScanAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRevision")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VirtualLibraryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CatalogueStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_CatalogueStates_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumSourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtworkTrackSourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grouping")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCompilation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Performance")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkSourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumSourceId");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CatalogueTracks", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrackArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistSourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistSourceId");

                    b.HasIndex("TrackId", "ArtistSourceId")
                        .IsUnique();

                    b.ToTable("CatalogueTrackArtists", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrackGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreSourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreSourceId");

                    b.HasIndex("TrackId", "GenreSourceId")
                        .IsUnique();

                    b.ToTable("CatalogueTrackGenres", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrackStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Source")
                        .IsUnique();

                    b.ToTable("CatalogueTrackStatistics", null, t =>
                        {
                            t.HasCheckConstraint("CK_CatalogueTrackStatistics_Rating", "Rating BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueVirtualLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("CatalogueVirtualLibraries", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueVirtualLibraryTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeenRefreshId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackSourceId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("VirtualLibraryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeenRefreshId");

                    b.HasIndex("TrackSourceId");

                    b.HasIndex("VirtualLibraryId", "TrackSourceId")
                        .IsUnique();

                    b.ToTable("CatalogueVirtualLibraryTracks", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.HasIndex("TraceIdentifier");

                    b.HasIndex("OccurredAtUtc", "Id");

                    b.HasIndex("Source", "Area");

                    b.ToTable("ErrorLogs", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasFilter("\"CorrelationId\" IS NOT NULL");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("UX_Jobs_ActiveCatalogueRefresh")
                        .HasFilter("\"Type\" = 'catalogue.refresh' AND \"Status\" IN (0, 1)");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.HasIndex("Status", "RunAfterUtc", "Id");

                    b.HasIndex("Type", "Status", "Id");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Id");

                    b.ToTable("JobLogs", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityScheduledJobState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScheduledJobStates", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RatingMatch")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequestedKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolver")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolverVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RetrievalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ObservationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("SearchObservations", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("SearchObservationId", "Position")
                        .IsUnique();

                    b.ToTable("SearchObservationCandidates", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchObservationId", "Sequence")
                        .IsUnique();

                    b.ToTable("SearchObservationRequests", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedAlbum")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedArtist")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncludeInEvaluation");

                    b.HasIndex("SearchObservationId")
                        .IsUnique();

                    b.ToTable("SearchObservationReviews", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationCandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SelectedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchObservationCandidateId")
                        .IsUnique();

                    b.HasIndex("SelectedAtUtc");

                    b.ToTable("SearchObservationSelections", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityToolCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArgumentsTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ErrorLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResultTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCallId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ErrorLogId");

                    b.HasIndex("ToolCallId")
                        .IsUnique();

                    b.HasIndex("StartedAtUtc", "Id");

                    b.HasIndex("ToolName", "Status", "StartedAtUtc");

                    b.ToTable("ToolCalls", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrackArtist", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrack", "Track")
                        .WithMany("Artists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrackGenre", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrack", "Track")
                        .WithMany("Genres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrackStatistic", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrack", "Track")
                        .WithMany("Statistics")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueVirtualLibraryTrack", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueVirtualLibrary", "VirtualLibrary")
                        .WithMany("Tracks")
                        .HasForeignKey("VirtualLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualLibrary");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityErrorLog", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJobLog", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", "Job")
                        .WithMany("Logs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithMany("Candidates")
                        .HasForeignKey("SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationRequest", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithMany("Requests")
                        .HasForeignKey("SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithOne("Review")
                        .HasForeignKey("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", "SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", "SearchObservationCandidate")
                        .WithOne("Selection")
                        .HasForeignKey("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", "SearchObservationCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservationCandidate");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityToolCall", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityErrorLog", "ErrorLog")
                        .WithMany()
                        .HasForeignKey("ErrorLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ErrorLog");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueTrack", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Genres");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityCatalogueVirtualLibrary", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Requests");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.Navigation("Selection");
                });
#pragma warning restore 612, 618
        }
    }
}
