// <auto-generated />
using System;
using LyrionVoiceMcp.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LyrionVoiceMcp.Ef.Migrations
{
    [DbContext(typeof(LyrionVoiceMcpDbContext))]
    [Migration("20260818063431_AddOperationalPersistence")]
    partial class AddOperationalPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.HasIndex("TraceIdentifier");

                    b.HasIndex("OccurredAtUtc", "Id");

                    b.HasIndex("Source", "Area");

                    b.ToTable("ErrorLogs", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasFilter("\"CorrelationId\" IS NOT NULL");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("UX_Jobs_ActiveCatalogueRefresh")
                        .HasFilter("\"Type\" = 'catalogue.refresh' AND \"Status\" IN (0, 1)");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.HasIndex("Status", "RunAfterUtc", "Id");

                    b.HasIndex("Type", "Status", "Id");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Id");

                    b.ToTable("JobLogs", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityScheduledJobState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScheduledJobStates", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolver")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolverVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RetrievalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ObservationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("SearchObservations", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("SearchObservationId", "Position")
                        .IsUnique();

                    b.ToTable("SearchObservationCandidates", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchObservationId", "Sequence")
                        .IsUnique();

                    b.ToTable("SearchObservationRequests", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedAlbum")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedArtist")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncludeInEvaluation");

                    b.HasIndex("SearchObservationId")
                        .IsUnique();

                    b.ToTable("SearchObservationReviews", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationCandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SelectedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchObservationCandidateId")
                        .IsUnique();

                    b.HasIndex("SelectedAtUtc");

                    b.ToTable("SearchObservationSelections", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityToolCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArgumentsTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ErrorLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResultTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCallId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ErrorLogId");

                    b.HasIndex("ToolCallId")
                        .IsUnique();

                    b.HasIndex("StartedAtUtc", "Id");

                    b.HasIndex("ToolName", "Status", "StartedAtUtc");

                    b.ToTable("ToolCalls", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityErrorLog", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJobLog", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", "Job")
                        .WithMany("Logs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithMany("Candidates")
                        .HasForeignKey("SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationRequest", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithMany("Requests")
                        .HasForeignKey("SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithOne("Review")
                        .HasForeignKey("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", "SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", "SearchObservationCandidate")
                        .WithOne("Selection")
                        .HasForeignKey("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", "SearchObservationCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservationCandidate");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityToolCall", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityErrorLog", "ErrorLog")
                        .WithMany()
                        .HasForeignKey("ErrorLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ErrorLog");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntityJob", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Requests");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.Navigation("Selection");
                });
#pragma warning restore 612, 618
        }
    }
}
