// <auto-generated />
using System;
using LyrionVoiceMcp.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LyrionVoiceMcp.Ef.Migrations
{
    [DbContext(typeof(LyrionVoiceMcpDbContext))]
    [Migration("20260818054011_AddSearchObservations")]
    partial class AddSearchObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolver")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolverVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RetrievalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ObservationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("SearchObservations", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("SearchObservationId", "Position")
                        .IsUnique();

                    b.ToTable("SearchObservationCandidates", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchObservationId", "Sequence")
                        .IsUnique();

                    b.ToTable("SearchObservationRequests", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedAlbum")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedArtist")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchObservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncludeInEvaluation");

                    b.HasIndex("SearchObservationId")
                        .IsUnique();

                    b.ToTable("SearchObservationReviews", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchObservationCandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SelectedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchObservationCandidateId")
                        .IsUnique();

                    b.HasIndex("SelectedAtUtc");

                    b.ToTable("SearchObservationSelections", (string)null);
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithMany("Candidates")
                        .HasForeignKey("SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationRequest", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithMany("Requests")
                        .HasForeignKey("SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", "SearchObservation")
                        .WithOne("Review")
                        .HasForeignKey("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationReview", "SearchObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservation");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", b =>
                {
                    b.HasOne("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", "SearchObservationCandidate")
                        .WithOne("Selection")
                        .HasForeignKey("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationSelection", "SearchObservationCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchObservationCandidate");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservation", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Requests");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("LyrionVoiceMcp.Ef.Abstractions.Entities.EntitySearchObservationCandidate", b =>
                {
                    b.Navigation("Selection");
                });
#pragma warning restore 612, 618
        }
    }
}
